server:
  port: 9083
  
spring:
  application:
    name: lockerservice
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://microservices-eureka-service:8761/eureka/
  instance:
     hostname: lockerservice
